name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "10"
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: Install dependecncies
        run: npm install
      - name: Run test
        run: npm test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "10"
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: Install dependecncies
        run: npm install
      - name: Run Lint
        run: npm run lint
